# === Test ===============================================

mr:playwright:test:
  image: $DOCKER_IMAGE_GKE_SDK
  stage: test
  interruptible: true
  variables:
    # TODO: implement DRY_RUN option
    GKE_CONFIG_PATH: 'images/playwright/cloudbuild-test.yaml'
    GKE_SUBSTITUTIONS: '_NODE_VERSION=${NODE_VERSION},_PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION},_PNPM_VERSION=${PNPM_VERSION},_IMG_HOST=${IMG_HOST},_GOOGLE_PRID=${GOOGLE_PRID},_CI_PROJECT_NAME=${CI_PROJECT_NAME}'
  extends:
    - .gke-publish-preparation
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - "images/playwright/**"
  script:
    - ./images/playwright/prepare-build.sh && gcloud builds submit --config=${GKE_CONFIG_PATH} --substitutions=${GKE_SUBSTITUTIONS}
  tags:
    - build
